global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spark'
    metrics_path: /metrics
    static_configs:
      - targets:
          - spark-master:8090
          - spark-worker:8090

    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*driver.BlockManager.*|.*executor.*shuffle.*'
        action: drop
